# This is a basic workflow to help you get started with Actions

name: Lab 2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'lab2/**'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'lab2/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v2
        with:
          repository: catherine-leung/labtesters
          path: ./tester

      - name: Copy cpp tester files
        run: cp ./tester/lab2/*.cpp ./

      - name: Copy assignment files
        run: cp ./assignment/lab2/lab2.cpp ./


      # Runs a single command using the runners shell
      - name: Compile
        run: c++ lab2.cpp lab2tester.cpp -std=c++0x -o l2

      # Runs a set of commands using the runners shell
      - name: Run
        run: ./l2
